### ISSUE TITLE
Design Feature to GET Discord Service Status 

### ISSUE THREAD

**Issue by MaksymKarunos** [ahnaf-zamil/zenora#19]
**Is your feature request related to a problem? Please describe.**
While using Zenora, users can get bad responses from us even though it may not be our fault. For example, during a power out on the Discord server-side, Zenora 0.0.33v will send null responses.

The solution would be to offer users a condition of checking if the discord servers are up
We could implement a user-facing test function that is aiming to request some random data directly from Discord's REST and see if the data retrieved is not null.

**Comment by ahnaf-zamil** [comment]
The server doesn't send bad response because Discord is out. It may also send bad responses because the user inputted an invalid server id which Zenora can't check because all snowflakes are valid. So Discord may send bad responses that are handled by Zenora with ``raise_for_status()``. This function will raise an error if Discord sent bad response so the user knows what happened

**Comment by MaksymKarunos** [comment]
My bad, I am sorry I didn't go through all errors completely. Great job
