### ISSUE TITLE
Typo in refresh_access_token()

### ISSUE THREAD

**Issue by catto0** [ahnaf-zamil/zenora#24]
Hello, 

I recently used your api for a school project and after getting error while trying to refresh the access token I decided to look through your code and found out that you have a typo on line 64 in zenora/impl/oauthapi.py.

https://github.com/ahnaf-zamil/zenora/blob/1efb8f831e181bd1d0c73ba83e5417d71b5389cf/zenora/impl/oauthapi.py#L64

The ``` get_current_user ``` method is missing brackets, and so ``` current_user ``` is a function pointer instead of being the ``` OwnUser ``` object said method should return.

Possible fix:
```
current_user = self._app.users.get_current_user()
```

That being said, thank you for creating this, it saved me a bunch of time.

**Comment by ahnaf-zamil** [comment]
Hello. Thank you for making this issue, I really appreciate it. I can't believe this small project of mine is being used by someone for a school project. I never imagined it would reach this far. Anyways, let's get to business.

Firstly, I want to let you know that the current development of Zenora has been moved to [GitLab](https://gitlab.com/ahnaf-zamil/zenora). 

Regarding the typo, it has been fixed in the GitLab version. You can check it out [here](https://gitlab.com/ahnaf-zamil/zenora/-/blob/master/zenora/impl/oauthapi.py#L64). If you have no other problems, you may close this issue.

For making further issues, please make them on GitLab. I may revert the development of Zenora back to GitHub if a lot of people have issues with GitLab.
