### ISSUE TITLE
Placed zenora in app directory directly per instructions

### ISSUE THREAD

**Issue by Cupara** [ahnaf-zamil/zenora#9]
Since pip install didn't work to install the package I went with the second solution provided by your video on a Discord Login. When I go to run app.py I get this error:
`Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from zenora import APIClient
ModuleNotFoundError: No module named 'zenora'`

It's in the main directory of my app directory and the app.py file is in a subdirectory called back.

**Comment by ahnaf-zamil** [comment]
Hmm, I will have to take a look at it. Thank you for making the issue though

**Comment by ahnaf-zamil** [comment]
Could you send me a screenshot of your codebase directories and stuff? That would help me, since Python basically considers the directory where you run the app.py from as it's working directory.

Think of it like this. You have this structure (let us assume this is the root app directory)
```py
zenora
myapp
  - __main__.py
  - app.py
```

In your app.py code, you can have:
```py
from flask import Flask # Using Flask as example
import zenora

app = Flask(__name__)
...
```
And in your `__main__.py`, you can have:
```py
from .app import app # Relative import inside module structure since we are using __main__

if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=8080)
```

If you want to run this, you can do `python -m myapp`. Since your myapp "module" has an `__main__` file, you can use the `-m` to run it.

But if you `cd` into `myapp` and then run `app.py`, it wouldn't be able to find zenora as the working directory becomes `myapp` and the `zenora` is outside of that directory, hence it's unresolved.

Although, I think I should add a `__main__.py` file to the examples so that people don't face the same issue

**Comment by ahnaf-zamil** [comment]
I added some instructions as well as the `__main__.py` for the examples with commit https://github.com/ahnaf-zamil/zenora/commit/b61237150ca7782c2b28352393b08759b4803276

So for now, I'm closing this issue. You can reopen it if your problem still remains unresolved.
